### PR TITLE
Show the license warning upon startup if MN not licensed

### PR DESCRIPTION
**Pull request by alexbikfalvi**
This changes verifies at the CLI startup the current license
status, and if the valid flag is false, it displays a warning
message to the user with the license status message.

This patch also fixes a minor inconsisteny in the naming
of the license status object type: license_status > license-status

Ref: MN-2498

Signed-off-by: Alex Bikfalvi alex.bikfalvi@midokura.com

### CODE REVIEW

**Comment by srvaroa** [comment]
LGTM

**Comment by alexbikfalvi** [comment]
@srvaroa Actually, it seems that the commit was already merged, strange that GitHub returns the message that it can't merge.

**Comment by srvaroa** [comment]
Mm yes, it looks like the commit is in both master and 1.5.0, can you quickly check if the contents are right? in that case we can just close this one.

**Comment by alexbikfalvi** [comment]
I checked the content is okay. I'm closing the pull request.

**Pull request closed without merging**
