### PR TITLE
Allow CLI users to use API names.

### PR DESCRIPTION
**Pull request by jlmjlm**
Signed-off-by: Jacob Mandelson jlm@midokura.com

### CODE REVIEW

**Comment by admytren** [comment]
@jlmjlm @gontanon 
Just talked to Jacob. This change makes it possible to use both object names registered in CLI and their corresponding object names in REST api. My opinion is that accepting both makes CLI more complex and at best encourage 2 different syntax types to be used for the same task and at worst be a hidden feature that is only used by subset of engineers intimately familiar with REST api naming.

If this is an issue that makes it very inconvenient for developers, could we consider synchronizing object names in CLI and REST API as an alternative to accepting both?

**Comment by jlmjlm** [comment]
I just had a spirited argument with Artem about this.  He is steadfast on
his opinion that the CLI only accept one set of names, and I am steadfast
in my opinion that the names which are documented in the API be accepted.
My argument is that this change doesn't break anyone, as CLI names are
still accepted, but fixes the behavior for people who know the documented
API names but not the undocumented CLI ones.  As it harms nobody and helps
people familiar with the API, I think it is strictly an improvement.

**Comment by gdecandia** [comment]
@jlmjlm @admytren Guys, could you give some examples of semantically equivalent commands that would be allowed if this change is merged?

@tfukushima Taku, how will this change affect the UI? Will it still be possible to keep syntactic equivalence between the CLI and the GUI's auto-complete text-boxes?

**Comment by jlmjlm** [comment]
Example:
"router router0 add port type ExteriorRouter address 10.2.14.74 net
10.2.14.0/24"
would work in addition to
"router router0 add port type exterior address 10.2.14.74 net 10.2.14.0/24"

Autocompletion fails for port types both before and after this change.

**Comment by gontanon** [comment]
Hi guys, my 2c:

I don't have a very strong opinion about this, but I lean towards Artem's position, I prefer to have one consistent syntax, mostly because code/command examples get shared and it can be confusing to new users to see people throwing around commands with both styles. I think it gives a more cohesive feel.

It's also true that 'enum' values in the CLI were pretty much hidden unless you saw the CLI print a similar object to take as example, because they were undocumented and because of the autocomplete bug. Hopefully the new manpages will solve that:

https://github.com/midokura/python-midonetclient/pull/38

I've also opened an issue about the autocomplete problem.

**Comment by rossella** [comment]
Everyone agree if I close this pull request? @admytren @gontanon ?

**Comment by admytren** [comment]
Yeah, I still have the same opinion that it would be too many ways to accomplish the same task. And that may be user unfriendly.

**Pull request closed without merging**
