### PR TITLE
Fix midonet-cli for packet tracing

### PR DESCRIPTION
**Pull request by takayukiu**

### CODE REVIEW

**Comment by tomoe** [comment]
Thanks @takayukiu , could you change the commit message? this is going to master, which we call E release, not 1.3 anymore.

**Comment by tomoe** [comment]
ping @takayukiu

**Comment by takayukiu** [comment]
The message has been slightly changed. Don't you like it?

**Comment by tomoe** [comment]
Ah, sorry, I missed it. LGTM.

**Comment by tfukushima** [comment]
LGTM

**Comment by tomoe** [comment]
Thanks @tfukushima, @takayukiu. merging

**Pull request merged**
