### PR TITLE
Removes the VTEP name setter.

### PR DESCRIPTION
**Pull request by tomohikokimura**
The VTEP name is always set by the system and not to be set by the
client. This patch removes the setter for the VTEP name from Python
MidoNet Client Vtep class.

Fix MN-2510

### CODE REVIEW

**Comment by tomohikokimura** [comment]
Hey, Brandon!

Can you please take a look at this pull request?

Thanks!
Tomohiko

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
API team is looking into the failure, checking if it's related to this change, which is unlikely. Thanks for the patience.

**Comment by tomoe** [comment]
This patch is okay as far as gating job is concerned. it's hitting some other issues.

**Comment by tomohikokimura** [comment]
Thanks for letting me know, Tomoe.

**Comment by brandon-berg** [comment]
Looks good.

**Pull request merged**
