### PR TITLE
VxGW: introduce addVtepTunnelZone to application

### PR DESCRIPTION
**Pull request by srvaroa**
Signed-off-by: Galo Navarro galo@midokura.com

### CODE REVIEW

**Comment by tomoe** [comment]
Disregard the message "Merged build triggered"; CI is still in progress.

**Comment by tomoe** [comment]
ok to test

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
Sorry for the noise. Please ignore my comments. I'm testing a jenkins CI job.

**Comment by alexbikfalvi** [comment]
LGTM, but I will test it just to be sure.

**Pull request closed without merging**
