### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by tomoe**
Please ignore

### CODE REVIEW

**Comment by tomoe** [comment]
ok to test

**Comment by tomoe** [comment]
test this please

**Comment by AbelNavarro** [comment]
I'm so tempted to merge this pull request... :)

**Comment by tomoe** [comment]
@abel-navarro you have lots of things to take care of. forget about this :-)

**Comment by AbelNavarro** [comment]
oh nice! you can link it to Jenkins.

**Comment by tomoe** [comment]
@abel-navarro yes. there's a plugin to look at pull reqs, which i'm playing around with here.

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
Sorry for the noise everybody, but please keep this pull req until I finish up CI setup.

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
Dear Jenkins, retest this please

**Pull request closed without merging**
