### PR TITLE
Rename MidoNet CLI to "midonet-cli"

### PR DESCRIPTION
**Pull request by admytren**
Hi team!

What do you think about naming our CLI utility "midonet-cli". Please refer to issue #16 for full discussion on this topic.

Thanks!
Artem

### CODE REVIEW

**Comment by gontanon** [comment]
+1.

**Comment by tomoe** [comment]
+1

**Comment by tomoe** [comment]
@admytren could you submit this to v1.1 as well?

**Comment by gontanon** [comment]
Hi @tomoe, could you clear that with @yoshiat? He's been coordinating the documentation for the release and I think it has mn-ctl all over the place?

**Comment by tomoe** [comment]
Hi @gontanon. Thanks for the heads up. Will poke the PM.

**Comment by yoshiat** [comment]
Sorry, I got mixed up on this.  There are only two places to replace in the
installation guide and the impact seems to be limited.  Please go ahead and
change it before we release v1.1.

**Comment by gontanon** [comment]
Submitted and merged to v1.1.

**Comment by yoshiat** [comment]
Thanks!

**Pull request merged**
