### PR TITLE
VTEP binding delete accepts only a single binding.

### PR DESCRIPTION
**Pull request by tomohikokimura**
This fixes the issue with the previous VTEP binding deletion patch
that it allowed the user to delete multipe VTEP bindings at once,
which is not consistent with the existing deletion semantics. This
patch enforces the uniqueness of the binding deletion by reusing the
ObjectFromCollection construct. It also extends the accepted deletion
expressions to include "delete PARENT-COLLECTION CHILD-COLLECTION".

Fix MN-1824

### CODE REVIEW

**Comment by tomohikokimura** [comment]
Hello @gontanon ;

Here's a patch that reuses ObjectFromCollection so that it won't delete multiple bindings at once. We'd still need the grammar extensions since new patters had not been covered by the patters prior to VTEP. @srvaroa, @ryu25ish , I'd appreciate if you two can also take a look.

Best,
Tomohiko

**Comment by ryu25ish** [comment]
@tomohikokimura sorry for the late reply.  I think this is a good implementation of this feature.  LGTM.  @gontanonm, @srvaroa , do you have strong opinions otherwise?

**Comment by gontanon** [comment]
+2 Thanks @tomohikokimura :)

**Comment by tomohikokimura** [comment]
Thanks, @gontanon and @ryu25ish . I'm merging this now.

**Pull request merged**
