### PR TITLE
Adds support for a VTEP tunnel zone type

### PR DESCRIPTION
**Pull request by alexbikfalvi**
This patch adds support for a VTEP tunnel zone type,
for network topologies that need to configure a physical
VTEP.

Fixes: MN-2573

Signed-off-by: Alex Bikfalvi alex.bikfalvi@midokura.com

### CODE REVIEW

**Comment by midosaba** [comment]
Merged build triggered. Test FAILed.

**Comment by midosaba** [comment]
Merged build started. Test FAILed.

**Comment by midosaba** [comment]
Merged build finished. Test FAILed.

**Comment by tomoe** [comment]
Please disregard the message from midosaba for now. He's not ready yet.

**Pull request merged**
