### PR TITLE
Tenant id may be in UUID or Keystone ID format

### PR DESCRIPTION
**Pull request by admytren**
This patch makes CLI accept tenant ID in either UUID or Keystone ID format. This patch fixes issue #19.

Tested this patch by successfully creating and deleting a router:

```
midonet> create router name 'new router'
router0
midonet> list router
router router1 name MidonetProviderRouter
router router0 name new router
router router2 name MidonetMetadataRouter
midonet> delete router router0
midonet> list router
router router1 name MidonetProviderRouter
router router2 name MidonetMetadataRouter
midonet> quit
```

### CODE REVIEW

**Comment by tomoe** [comment]
@admytren thanks for working on this!
Could you make it a generic string since tenantId in MidoNet API is string (see router resource for example: https://github.com/midokura/midonet/blob/master/docs/rest-api-specification.md#router-applicationvndorgmidonetrouter-v1json)

We have user(s) who use(s) MidoNet without OpenStack and also it would be handy for testing with arbitrary string.

Thanks!

**Comment by gontanon** [comment]
Thanks guys, @tomoe that makes sense, I wasn't really sure that requiring a UUID for the tenant was necessary.

**Comment by admytren** [comment]
Curt, it looks like the code has an intention of being able to specify the tenant id in the command itself. This is a command line interface, so the performance doesn't matter much and I think having more flexibility in code is a benefit.

Tomoe, I will change this to a string value.

**Comment by 0cjs** [comment]
@admytren: I was trying to say that validation should be done as early as possible, so you catch errors as close to the source as possible. In that context, I don't understand your reply, so maybe you can grab me on chat next time you get a chance?

**Comment by admytren** [comment]
Hi Curt, sorry I wasn't clear. What I was trying to say is that "tenant id" field is technically part of CLI commands, e.g. "create router name test [tenant tenant-id]". However, it's appended programmatically by python code to relevant commands. You're right that the value should be validated on when it's specified in the command line arguments or in the configuration file. However, please see Tomoe's comment - the tenant id is now a string and really doesn't do any validation.

**Pull request closed without merging**
