### PR TITLE
Adds support for a VTEP tunnel zone type

### PR DESCRIPTION
**Pull request by alexbikfalvi**
This patch adds support for a VTEP tunnel zone type,
for network topologies that need to configure a physical
VTEP.

Fixes: MN-2573

Signed-off-by: Alex Bikfalvi alex.bikfalvi@midokura.com

### CODE REVIEW

**Comment by alexbikfalvi** [comment]
Patch already merged in v1.5 branch.

**Comment by tomoe** [comment]
retest this please

**Comment by alexbikfalvi** [comment]
@tomoe @srvaroa Do you know how can I retrigger the tests for this patch? Jenkins doesn't seem to have an option.

**Comment by srvaroa** [comment]
LGTM.

No idea about the testing, @tomoe is setting that up - (do you have details on where this runs? anything we can do to help out?)

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
be polite to Mr. Jenkins :-)  
I think this patch has nothing to do with failures, but I just retriggered to make sure that's the case. 
Will update how it goes. Sorry for the inconvenience.

**Comment by tomoe** [comment]
This is good to merge. 
The test failed because of a regression, which is nothing to do with this patch.

**Pull request merged**
