### PR TITLE
Added Vlan aware bridge and ports

### PR DESCRIPTION
**Pull request by rossella**
Signed-off-by: Rossella Sblendido rossella@midokura.com

### CODE REVIEW

**Comment by srvaroa** [comment]
@tomoe ping

**Comment by tomoe** [comment]
Sorry I have been blocking this...
So, I heard that VAB would be going away, but this code looks like for VAB. Is this code still valid?
Looking at the current API spec(https://github.com/midokura/midonet/blob/master/docs/rest-api-specification.md)
I couldn't find "vlanBridges" in Application resource.

**Comment by srvaroa** [comment]
Hi @Tomoe, sorry for the confusion:

The documentation for the vlan-aware bridge is here: https://github.com/midokura/midonet/blob/master/docs/rest-api-specification.md#vlanawarebridge

This device will be removed later but not yet so it'll be supported. There are further changes being merged soon into master that are now in review (the most relevant is https://reviews.midonet.org:8443/#/c/783/)

I just noticed that I pinged you from the wrong pull request, it should be: https://github.com/midokura/python-midonetclient/pull/12, which includes changes also to the normal bridge. I think we can probably close this pull request.

**Comment by gdecandia** [comment]
> This device will be removed later but not yet so it'll be supported.

Hi @rossella - I don't understand "but not yet so it'll be supported".

The new device and associated API calls were added in master after 1.0 but before 1.1 and deprecated before 1.1's release. So it's much easier to simply not support it.

I would suggest at least removing the documentation (before the 1.1 tag) for the deprecated (and never released) API calls. The VAB (vlan-aware bridge) should never be supported since the normal virtual bridge already supersedes it.

**Comment by srvaroa** [comment]
I'm not sure the API calls even got to be merged into the client's repo. 

I think the removal of documentation makes sense as long as it's not a problem to have that "secret" feature undocumented. I updated the CR with the commit dedicated to documentation from my last batch of changes.

Let's abandon this code review and keep #12 only.

**Comment by gontanon** [comment]
@srvaroa , if we abandon this pull request, please note that there are unaddressed comments in this review, and #12 is a superset of this one.

**Comment by srvaroa** [comment]
I'm abandoning #12 too since it drags this commit, and creating a separate pull request with just the changes in the bridge.

**Comment by tomoe** [comment]
abandoning as @srvaroa suggested

**Pull request closed without merging**
