### PR TITLE
Initial CLI implementation

### PR DESCRIPTION
**Pull request by gontanon**

### CODE REVIEW

**Comment by tomoe** [comment]
Thanks Guillermo. This is great! I'm having an issue with auth from MN API. I'm looking at it now.

**Comment by tomoe** [comment]
Here're some issues I found while playing around with CLI:
- tenant name given by --tenant=XXX isn't respected
- i changed the code as follows and I'm able to log in now by supplying
  admin's user, password, and tenant name in KS (not tenant id)

```
diff --git a/src/bin/mn-ctl b/src/bin/mn-ctl
index 72dcd4f..56bb62a 100755
--- a/src/bin/mn-ctl
+++ b/src/bin/mn-ctl
@@ -142,7 +142,8 @@ class Session():
         logging.basicConfig()
         logger = logging.getLogger('midonet.api')
         logger.setLevel(logging.CRITICAL)
-        return MidonetApi(self.api_url, self.username, self.password)
+        return MidonetApi(self.api_url, self.username, self.password,
+                          self.tenant_id)


 ################################################################################
```
- However, the tenant name passed in to the command line arg is used for listing resources and there doesn't seem to be a way to pass in a tenant ID.  So, the authenticated admin user cannot list resources for tenants.
- While I was working on auth setting last week, i found that API server expects tenant name string instead of tenant id string stored in Keystone( https://github.com/midokura/midonet/blob/master/docs/rest-api-auth.md ). The admin user logged in with tenant name string in a CLI session can't even list their own resources since the resources have keystone tenant id string inside. We might want to change the API server (or add an option) to accept tenant id for login to be consistent with data stored in resources; I will file an issue for that.

**Comment by gontanon** [comment]
Thanks a lot @tomoe, I'm using mock auth and usually don't care about the tenant, so I'm not surprised that's broken.

Should we then wait for that issue to be fixed in the API or leave it as a known issue for now?

**Comment by tomoe** [comment]
Hi @gontanon Thanks for the prompt response. 
Could you work on list command to accept a tenant id, which i think is orthogonal to the auth issue. 
The syntax would be something like 
-  midonet> list router <tenant_id> 

? Or would you have a problem with that to differentiate ones with tenant_id and ones without?

**Comment by gontanon** [comment]
Sure, that should take me zero time. Question: should the user specify the
tenant_id in the list command explicitly or can we implicitly add the
tenant_id of the session to all commands that need it? (I'm sorry but I
don't know enough about how tenant ids are used or where they are
required).

On Mon, May 27, 2013 at 5:13 PM, Tomoe Sugihara notifications@github.comwrote:

> Hi @gontanon https://github.com/gontanon Thanks for the prompt
> response.
> Could you work on list command to accept a tenant id, which i think is
> orthogonal to the auth issue.
> The syntax would be something like
> - midonet> list router
> 
> ? Or would you have a problem with that to differentiate ones with
> tenant_id and ones without?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/midokura/python-midonetclient/pull/8#issuecomment-18503197
> .

## 

-- Guillermo Ontañón

**Comment by gontanon** [comment]
Hi @tomoe, just one more thing. Do you see any problem with doing the merge as is, leaving these issues to after the merge? Once it's merged people working on other midonet features can add them to the CLI in parallel and the whole team can start filing bugs and feature requests, it should speed things up.

**Comment by tomoe** [comment]
> Question: should the user specify the tenant_id in the list command explicitly or can we implicitly add the tenant_id of the session to all commands that need it?

I think it should be a explicit command arg; the main usecase would be that the admin user logs into the system and do some queries and/or operations for tenant resources as well. It'd be annoying if I had to get out of a session to see resources for another tenant. 

> Do you see any problem with doing the merge as is,

No problem. I can merge once list with tenant id gets in; I'd like to merge the code that's in a working state. Is it OK? or would you prefer merging even now?

**Comment by gontanon** [comment]
Thanks, sounds good, I'll add the parameter tonight and we can merge
tomorrow. So it'll look like this:

```
midonet> router list tenant <UUID>
```

This should still work too:

```
midonet> router list
```

Cheers,
G

On Mon, May 27, 2013 at 6:28 PM, Tomoe Sugihara notifications@github.comwrote:

> Question: should the user specify the tenant_id in the list command
> explicitly or can we implicitly add the tenant_id of the session to all
> commands that need it?
> 
> I think it should be a explicit command arg; the main usecase would be
> that the admin user logs into the system and do some queries and/or
> operations for tenant resources as well. It'd be annoying if I had to get
> out of a session to see resources for another tenant.
> 
> Do you see any problem with doing the merge as is,
> 
> No problem. I can merge once list with tenant id gets in; I'd like to
> merge the code that's in a working state. Is it OK? or would you prefer
> merging even now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/midokura/python-midonetclient/pull/8#issuecomment-18506134
> .

## 

-- Guillermo Ontañón

**Comment by gontanon** [comment]
Hi @tomoe,

Instead, I've added two new commands: pusht/popt, they work like pushd/popd do in bash, only for the session's tenant id instead of the current dir (the session's tenand id was already being used in create/list commands). This should require less typing.

**Comment by tomoe** [comment]
@gontanon Merging this now. I was hoping to fully understand the code, but it looks like it won't happen soon...

**Pull request merged**
