### PR TITLE
Add tunnel zone creations by type to api

### PR DESCRIPTION
**Pull request by srvaroa**
Signed-off-by: Galo Navarro galo@midokura.com

### CODE REVIEW

**Comment by admytren** [comment]
There is a lot of code duplication. Any reason not to pass the type as a parameter?

**Comment by alexbikfalvi** [comment]
LGTM
Artem is right that passing the tzone type as a parameter would remove some code duplication, which is more elegant and makes it easier to change tunnel zone types in the future. The only difficulty now is that different tunnel zones use different media types and it looks like application.py was intended to hide these details. A single method would therefore have to use a bunch of ifs in the simplest case to determine the correct media type.
Since now we only have three tzone types, if Galo is comfortable with his commit, he can merge.

**Comment by admytren** [comment]
@alexbikfalvi - take a look at the submitted code - it appears to be using the same media type for both tunnel zones

**Comment by alexbikfalvi** [comment]
@admytren Two of them yes, true, but GRE is using a different one. We should have one method for all three, isn't it?

**Comment by admytren** [comment]
Yes, you're right! The code looks good otherwise!

**Comment by intuitivepixel** [comment]
Hi guys, sorry to chime in,
but why does the creation of a vxlan or vtep "tunnel zone" use the "tunnel
zone host" media type APPLICATION_TUNNEL_ZONE_HOST_JSON instead of the
generic "tunnel zone" media type APPLICATION_TUNNEL_ZONE_JSON?

**Comment by tomoe** [comment]
@srvaroa could you rebase?

**Comment by srvaroa** [comment]
Hi guys. I agree re. sharing code. However, as Alex explains, in practise I don't really think we benefit much from it:
- api.py: 2 methods of 2 lines each, one of which is different in each case. Sharing code would require adding one extra method with a parameter, an if clause, etc. We'd end up writing more code (hence more surface area for bugs).
- application.py: 2 methods calling a single constructor and sharing all parameters but one. Here reusing the TZ construction based on a parameter would be easier, but would still require an additional method (and overall require more code lines, same reasoning).

Since both of the solutions imply writing more code than the current patch, it defeats the point of reusing code IMO. I do think if we have more tunnel zones we should to unify these, and also unify the TunnelZoneHost media types (I don't know why they are separate, @ryu25ish might know). But for this patch I don't think we get much benefit from reusing (rather the opposite).

What do you guys think?

**Comment by ryu25ish** [comment]
While I agree that we should change the interface to accept the type as a param, as @srvaroa said, I think we should address that in a separate patch.  

@intuitivepixel you can specify different tunnel types (GRE, VXLAN) in a particular tunnel (per host interface).  So a tunnel zone object is different from a tunnel zone - host mapping object.

**Comment by intuitivepixel** [comment]
@ryu25ish https://github.com/ryu25ish thanks for the explanation, I get
that I guess, what I don't understand is why the code is using the tunnel
zone host type but creating a tunnel zone and not a hot mapping object?

**Comment by ryu25ish** [comment]
@intuitivepixel sorry I gave you a wrong info.  Looking at the API code, tunnel zone type is specified at the tunnel zone level, not the mapping.  Either this was changed recently or I am incapable of remembering things..

**Comment by ryu25ish** [comment]
@srvaroa could you rebase?

**Comment by srvaroa** [comment]
@ryu25ish  sorry I didn't notice it was out of date. Done

**Comment by srvaroa** [comment]
I won't merge this since there seem to be some failing tests. Are these actually running officially? Where can I see failures? (@tomoe are you the man for this?)

**Comment by tomoe** [comment]
retest this please

**Comment by tomoe** [comment]
@srvaroa yes, i'm the man atm. just retriggered.

**Comment by tomoe** [comment]
Test is good for this patch, though it failed for another reason.

**Pull request merged**
