### PR TITLE
CLI Delete and Show grammar extension for collection.

### PR DESCRIPTION
**Pull request by tomohikokimura**
Extends the grammar for the CLI Delete and Show commands to handle
- show field for object collection, and
- delete elements in a sub-collection under a top-level collection.

-Sample CLI inputs:-
**To show the VTEP name**

> vtep management-ip 119.15.112.22 show name

**To delete bindings**

> vtep management-ip 119.15.112.22 delete binding vlan XXX
> vtep management-ip 119.15.112.22 binding delete network-id YYY

Note:
- The above delete commands can delete multiple resources (bindings).
- To delete, at least 1 or more filters (e.g. vlan id, network ID)
  need to be specified. The following delete-all command is invalid:

> vtep management-ip 119.15.112.22 binding delete

Fix MN-1824

### CODE REVIEW

**Comment by tomohikokimura** [comment]
Hello @gontanon ;

Could you please take a look at this new pull request? This implements the Delete / Show CLI grammar extensions for VTEP bindings.

Thanks,
Tomohiko

**Comment by tomohikokimura** [comment]
Reassigned to @srvaroa . Galo, I think it's ready to be merged. But please take a look for sanity check.

**Comment by brandon-berg** [comment]
I'm a bit worried by the fact that by omitting a filter, you can change a command from "Delete one object from a collection" to "Delete all objects in the collection." Seems like the sort of thing someone might accidentally do. I think I would prefer that the user have to explicitly specify "binding delete all" rather than just "binding delete".

It appears that the change you made also allows this syntax for resource types other than VTEP bindings, which makes me a bit more nervous about this.

I'm not going to insist on that change, but I'd like to see someone else review it.

**Comment by srvaroa** [comment]
I agree with that concern, but I'd condition whether to do it or not to what's the current convention in the rest of the CLI.

**Comment by tomohikokimura** [comment]
Thank you for your review, @brandon-berg and @srvaroa . I tweaked the grammar so that it would require at least 1 or more attribute filters. Since there are no other concerns, I'm merging this now.

**Comment by gontanon** [comment]
Hey guys,

Sorry I'm late to this conversation. Please disregard my comments if you've
already discussed the trade offs.

IIRC the "deletion by filter" feature already worked but only if your
filter was unambiguously matching on a single child. I may be be totally
off, this is what I recall, my personal preference is to keep things that
way because of the risk of a user losing data by deleting more than he
wanted, keeping in mind that the CLI does not print what it deleted, I
think extra carefulness is a good thing.

Regardless, a manpage update should probably go with this patch.

Cheers,
G

**Comment by gontanon** [comment]
Hello Guillermo;

I just extended the grammar for DELETE, but not the logic for handling list
filter itself, and it allowed me to delete multiple entities without
uniquely identifying the target. I made sure that a user had to specify at
least 1 list filter, and I think that that would be sufficient for this
particular use case. An alternative would be to make the user specify all 3
filters, but I'm not sure if we can write such a constraint in a generic
enough way.

Thank you for reminding me about the man page. I'll update it as well.

Thanks,
Tomohiko

**Comment by gontanon** [comment]
Hi @tomohikokimura,

My explanation was unclear. What I meant is that the grammar for delete already was supposed to take this into account. Otherwise it would have been impossible to delete port bindings (maybe there was a bug?). 

This is implemented in the "ObjectFromCollection" token, from which I paste this excerpt:

``` python
        elems = obj.fetch_all_for_type(collection.name, collection_filter)
        if len(elems) != 1:
            return ParsingSubmatch(context)
```

As you see the ObjectFromCollectionToken requires that the filter unambiguously identifies a single collection element to avoid spurious deletions. And this was part of the DELETE grammar already:

``` python
        obj_from_col = ObjectFromCollection()
        obj = ObjectById()

        patterns = delete + obj("+") + obj_from_col("*")
```

It could be ObjectFromCollection, or the patterns in DELETE were buggy. It try to delete a port binding or a dhcp subnet with a version of the CLI that does not have this patch, to verify.

In anycase, this patch makes the grammar contain two different patterns to remove via list filters. In my opinion we should stick to one of them only.

**Comment by srvaroa** [comment]
@ryu25ish could you take a look at this one? I am not familiar at all with the CLI and I think you should have the last say on API + CLI matters. Specially in CLI, I think we should be very careful on keeping a consistent behaviour here since it's a user-facing tool. 

I don't see a clear agreement from the comment history on the following points, so I think these should be clarified and if needed, addressed with either further patches or reverts:
- Whether the pattern change is really necessary. What I can understand from @gontanon 's comments is that deletes should be working even for entities that don't have an ID (by passing a list of k-v fields that identify a single element). From T's comments I understand this doesn't work: could we clarify why? Do we really need grammar changes (in which case, see next point) or is it due to a bug (in which case we should fix the bug).
- If we need a pattern changes, I share the concern re. single/multiple deletes: I think this is a risky change and don't see a clear agreement on an approach from the list of comments. I'd like to see what's @ryu25ish 's take on this but IMO, we should have a single pattern (whichever is deemed best) and in case of changes we should follow up with documentation updates.

Thanks!

**Comment by tomohikokimura** [comment]
Hello Galo, Guillermo and Ryu;

> - Whether the pattern change is really necessary. What I can
>   understand from @gontanon https://github.com/gontanon 's comments is
>   that deletes should be working even for entities that don't have an ID (by
>   passing a list of k-v fields that identify a single element). From T's
>   comments I understand this doesn't work:
> 
> No, that's not what I'm saying. We can delete things that don't have a
> unique ID. This is already being done. The case in question is whether we
> should allow deletion of multiple items. With a hint from Guillermo in his
> email just before this., I think I can reuse the existing construct to
> enforce the uniqueness of delete targets. I'll prepare a patch for that.
> - could we clarify why? Do we really need grammar changes (in which
>   case, see next point) or is it due to a bug (in which case we should fix
>   the bug).
> 
> We'd still need a grammar rule addition, since the VTEP deletion case
> presents us a new pattern of "COLL-WITHOUT-ID delete SUB-COLL-WITHOUT-ID",
> which hadn't been covered by the pre-existing rules.
> - If we need a pattern changes, I share the concern re.
>   single/multiple deletes: I think this is a risky change and don't see a
>   clear agreement on an approach from the list of comments. I'd like to see
>   what's @ryu25ish https://github.com/ryu25ish 's take on this but
>   IMO, we should have a single pattern (whichever is deemed best) and in case
>   of changes we should follow up with documentation updates.
> 
> Now I know a way to enforce uniqueness on delete, but it's an orthogonal
> discussion whether we really should enforce it on VTEP deletion or should
> allow the user to delete multiple items for usability.

Best,
Tomohiko

**Comment by gontanon** [comment]
"We'd still need a grammar rule addition, since the VTEP deletion case
presents us a new pattern of "COLL-WITHOUT-ID delete SUB-COLL-WITHOUT-ID",
which hadn't been covered by the pre-existing rules."

Oh, I didn't know you had two levels of "no-id" collections. In theory the pre-existing pattern should have worked with that:

``` python
patterns = delete + obj("+") + obj_from_col("*")
```

...because it allows multiple instances of 'obj_from_col'. But ObjectFromCollection is most certainly buggy for this case, I don't think it was in my radar.

**Comment by tomohikokimura** [comment]
Hello Guillermo;

Oh, I didn't know you had to levels of "no-id" collections. In theory the

> pre-existing pattern should have worked with that:
> 
> patterns = delete + obj("+") + obj_from_col("*")
> 
> ...because it allows multiple instances of 'obj_from_col'. But
> ObjectFromCollection is most certainly buggy for this case, I don't think
> it was in my radar.

obj = ObjectByID(), so I don't think it'll cover the case in question.
Furthermore, it seems more natural for us to allow an expression:

VTEP delete VTEP-binding

where delete is in between the parent and its child.

Tomohiko

**Comment by tomohikokimura** [comment]
@guillermo, @galo, @ryu

I prepared a new patch enforcing the uniqueness of VTEP binding delete:

https://github.com/midokura/python-midonetclient/pull/202

The grammar extensions are still necessary for the reason I explained in my
previous message. The new expressions hadn't been covered by the prior
grammar patterns.

Tomohiko

**Comment by gontanon** [comment]
ah, right right, it was the grammar, not ObjectFromCollection that didn't take that case into consideration.

I shouldn't have doubted my implementation of ObjectFromCollection :-P.

Thanks!

**Pull request merged**
