### PR TITLE
CLI can show VTEP configurations.

### PR DESCRIPTION
**Pull request by tomohikokimura**
- Can display full configuration info such as connection state.
- Can list all the bindings for a VTEP.

Sample CLI command lines:

midonet> vtep list
name br0 management-ip 119.15.112.22 management-port 6633 connection-state CONNECTED
midonet> vtep management-ip 119.15.112.22 list binding
management-ip 100.100.100.1 physical-port eth0 vlan 201 network-id ca07e054-2cef-4b6e-8d0a-c3b8e747615b
management-ip 100.100.100.2 physical-port eth0 vlan 202 network-id 60e94be7-276b-4eec-a845-f16671f01467

Fix MN-1638

### CODE REVIEW

**Comment by tomohikokimura** [comment]
Confirmed that it's working. I'm merging this shortly.

**Comment by AbelNavarro** [comment]
remember that you have to update Midonet repository to point to the latest changes in python-midonetclient.

**Comment by srvaroa** [comment]
Thanks @abel-navarro !

@tomohikokimura can you push the submodule update?

**Comment by tomohikokimura** [comment]
@abel-navarro @srvaroa My git magic power is limited... Would you please enlighten me on how I can update git submodule?

**Comment by srvaroa** [comment]
Hi @tomohikokimura 

So, on the midonet project, tip of master (or 1.4 branch, as appropriate)

git submodule init
git submodule update
cd python-midonetclient
git fetch origin
git checkout origin/master # or v1.4

# make sure your commit appears here, usually it'll be the tip

cd ..
git status # should show that you have modified python-midonetclient
git add python-midonetclient # this will update the submodule ref. to the new revision you checked out above
git commit -s # Add commit message
git review master # or v1.4

Done!

**Pull request merged**
