### PR TITLE
L4lb

### PR DESCRIPTION
**Pull request by tfukushima**
This pull request is identical for #90 but targeting for `l4lb` branch instead of `v1.3`.
- Added the L4LB resources for `midonetclient` module
- Added the commands to `midonet-cli`

**NOTE:** Manually tested except for commands of `pool-statistic`, which is not implemented in the current `l4lb` branch.

### CODE REVIEW

**Comment by tfukushima** [comment]
Hi @gontanon,

I updated the CLI commands and now they're working for the new API model. Could you review the code and the manual, which contains the usage of the commands, placed under `doc` directory?

**Comment by gontanon** [comment]
Thanks Taku! Will review, tomorrow at the latest, unfortunately I have a
long backlog of reviews.

Regards,
G

**Comment by tomoe** [comment]
HI @gontanon 
Any chance you looked at it?

**Comment by tfukushima** [comment]
This pull request is abandoned because it should be created only against `master`.

**Pull request closed without merging**
